In [ ]:
import numpy as np 
def R2Net_predict(gt, x, learning_rate):
    #This function implements the R2Net to predict a block
    #Input arguments:
    #gt: ground truth block to be predicted, organized as a 1-column vector, normalized to [0,1]
    #x: feature vector for prediction, organized as a 1-column vector, normalized to [0,1]
    #learning_rate: learning rate

    #Output:
    #prediction: predicted block, organized as a 1-column vector, normalized to [0,1]
    
    #Initialize weights (W) and bias (b) to one   
    sb = len (gt)  # sb = size of gt
    sfv = len(x)   # sb = size of x
   
    W = np.ones((sfv,sb))
    b = np.ones((1,sb))
    er_p = np.zeros((sb,1))
    

   
    for it in (0, 1): #Two iterations of back-propagation (BP)
        #Forward propagation
        
        #Use W and b to compute prediction and then apply the Sigmoid activation function
        z = ( (W.transpose()).dot(x) + b.transpose())
        hz = applyactfunc(z)

        
        pred =  er_p + hz

        
        #Backward propagation to FC layer  
        if it==0:
            er =  gt - pred

            dW = -(x.dot(er.transpose())) #Opposite direction for gradient
        else:
            er =  pred - gt
            dW = (x.dot(er.transpose())) 

        db = er # np.mean(er, axis=0) #gradient for W
        db = db.transpose() #gradient for b

    
        er_p = er #update error
    
        #Gradient descent
        W = W - (learning_rate * dW)
        b = b - (learning_rate * db)
        
    return pred

In [3]:
def applyactfunc(z):
     #This function implements the Sigmoid activation function
    
    p = 1 + np.exp(-1*z)
    hz = np.divide(1,p)
    
    return hz

In [4]:
def R2Net_reconstruct(x, res, learning_rate):
    #This function implements the R2Net to reconstruct a block from its error signal
    #Input arguments:
    #x: feature vector used for prediction, organized as a 1-column vector, normalized to [0,1]
    #gt: error signal for a block, organized as a 1-column vector
    #learning_rate: learning rate

    #Output:
    #prediction: predicted block, organized as a 1-column vector, normalized to [0,1]
    
    
        er2 = -1*res
        
        #Initialize weights (W) and bias (b) to one   
        sb = len (gt)  # sb = size of gt
        sfv = len(x)   # sb = size of x
   
        W = np.ones((sfv,sb))
        b = np.ones((1,sb))
        er_p = np.zeros((sb,1))
        
        z = ( (W.transpose()).dot(x) + b.transpose())
        f1 = applyactfunc(z)
     
        f2 = er2 + er_p + f1
        
        #Inverse sigmoid
        f2i = np.log(f2) - np.log(1-f2)
        
        xt = x.transpose()
        scalar = xt.dot(x)
        er1 = (f2i - z)/((learning_rate*scalar)- learning_rate)

        #Compute the reconstructed ground truth
        rec = er1 + er_p + f1
        
        return rec

In [5]:
#Sample usage

#Sample 4X4 block of pixel values normalized to [0,1]. This block is to be predicted. 
#The block has been re-shaped to a 1-column vector gt
gt = np.array([[0.5234], 
               [0.4232], 
               [0.3435], 
               [0.3435], 
               [0.5645], 
               [0.5468], 
               [0.9564], 
               [0.3543], 
               [0.8564], 
               [0.5657], 
               [0.7847], 
               [0.9343], 
               [0.9341], 
               [0.2432], 
               [0.4543], 
               [0.3425]])

#Sample feature vector to predict the 4X4 block. The features are also pixel values normalized to [0,1]. 
#The feature vector is a 1-column vector x
x = np.array([[0.3421],
              [0.3243],
              [0.3432]])

#Learning rate for the R2Net
learning_rate = 0.5

#Compute and display the predicted block as a 1-column vector
pred = R2Net_predict(gt, x, learning_rate)
print(pred)

#Compute and display the error signal (original block - predicted block)
esignal = gt - pred
print("ERROR")
print(esignal)

#Compute and display the reconstructed block as a 1-column vector. 
#The reconstruction uses the error signal and feature vector x
rec = R2Net_reconstruct(x, esignal, learning_rate)
print(rec)

#Compute and display the mean difference between the original block and the reconstructed block
diff = gt - rec
md = np.sum(diff)/len (gt)
print(md)

[[0.53518171]
 [0.43808541]
 [0.36079667]
 [0.36079667]
 [0.57498505]
 [0.55784516]
 [0.95380991]
 [0.37127287]
 [0.8572709 ]
 [0.57614698]
 [0.78799922]
 [0.93248229]
 [0.93228926]
 [0.26346007]
 [0.46823076]
 [0.3598266 ]]
ERROR
[[-0.01178171]
 [-0.01488541]
 [-0.01729667]
 [-0.01729667]
 [-0.01048505]
 [-0.01104516]
 [ 0.00259009]
 [-0.01697287]
 [-0.0008709 ]
 [-0.01044698]
 [-0.00329922]
 [ 0.00181771]
 [ 0.00181074]
 [-0.02026007]
 [-0.01393076]
 [-0.0173266 ]]
[[0.5234]
 [0.4232]
 [0.3435]
 [0.3435]
 [0.5645]
 [0.5468]
 [0.9564]
 [0.3543]
 [0.8564]
 [0.5657]
 [0.7847]
 [0.9343]
 [0.9341]
 [0.2432]
 [0.4543]
 [0.3425]]
4.111294638065033e-16
